### PR TITLE
Fix/new rgl api

### PR DESCRIPTION
**Pull request by c43721**
Use the `disableCache` boolean for the new rgl api and refactor the rgl api function

### CODE REVIEW

**Comment by kblauhut** [comment]
If this is a release version can you update the manifest version too. I suggest v0.95 since I believe there is a uncommited version bump somewhere lol.

**Review by kblauhut — APPROVED** [review]

**Comment by c43721** [comment]
Also, look at #5, I can throw that in this release too.

**Review by kblauhut — APPROVED** [review]

**Comment by kblauhut** [comment]
> Also, look at #5, I can throw that in this release too.

Whoops was too fast with the merge button. Lets just do this for the next one. Looks awesome though had no idea that there was an action for this already.

**Comment by c43721** [comment]
Awesome! Merging changes into rgl-api and payload now.

Both are updated and are deploying, might see some errors pop up for ~5-10 minutes.

**Pull request merged**
